### ISSUE TITLE
get_nclimgrid_monthly:  URL Not Found

### ISSUE THREAD

**Issue by dbcrow** [toozler/noaa_nclimgrid_r#1]
Hi, André Ferreira-

My name is David Crow, of the Climate Change and Health Equity Branch of the California Department of Public Health. 

I'm trying to read in the gridded NClimGrid data with the "get_nclimgrid_monthly" function you've written. However, for the URL 'https://www.ncei.noaa.gov/pub/data/cirs/climgrid/2023.tave.conus.pnt', the function throws this error:  

404 Not Found

Do you have any workarounds--e.g., a new URL, modified function, etc.?  I'd be grateful for any assistance you could provide. 

Muito obrigado,
David

**Comment by toozler** [comment]
Hi David - Seems like NOAA changed the name for the continental US from "conus" to just "us" in their files. I'll push an update this weekend.

**Comment by dbcrow** [comment]
Many thanks, André, for pushing the update. Works perfectly. 

I'm not sure what I'm looking at, though. Not to abuse your generosity, but a few questions: 

1) on the monthly data, it's clear that all all months are from 2023, but how can I know what the years are for the normals, which go from 1901-2000? 

2) how is it that a year's worth of data and 100 years of data have nearly the same file size?  

Thanks,
David

**Comment by toozler** [comment]
The normals published by NOAA indicate the average measurements for a given month over the entire reference period - it will not contain values for specific years in that range. 

Getting averages for specific years prior to the recent year would require you downloading from the archive. The package does not have that functionality completed, although I have started to sketch it [here](https://github.com/toozler/noaa_nclimgrid_r/blob/18ccc6c83952a33888d1dfc92b62b664d967417b/R/utils.R#L175) but didn't complete.

It would be nice if the same format yearly "tave" and "precip" files were available in the their FTP in the same format as the most recent year.
